### PR TITLE
for loop python

### PR DESCRIPTION
**Pull request by raheemazeezabiodun**
A simple for loop in python

### CODE REVIEW

**Review by GersonLazaro — CHANGES_REQUESTED** [review]
Hi.
The filename must be for-loop.
Correct it to approve it :)
Thank you very much

**Comment by raheemazeezabiodun** [comment]
Okay, will do that

**Comment by raheemazeezabiodun** [comment]
done

**Review by GersonLazaro — APPROVED** [review]

**Comment by GersonLazaro** [comment]
Thanks!
:1st_place_medal:

**Pull request merged**
